// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4EmUMiSblxeCjJf5nJ2njJyBGItdU6Y',
    appId: '1:317294457408:web:26d3da2dcc98a8617365a5',
    messagingSenderId: '317294457408',
    projectId: 'project-1-212b6',
    authDomain: 'project-1-212b6.firebaseapp.com',
    databaseURL: 'https://project-1-212b6-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-212b6.appspot.com',
    measurementId: 'G-PERR0DLS40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdty7TQTHp7c47MF4xGgUMRRlRFSOV4DQ',
    appId: '1:317294457408:android:9cb57922583d2ec77365a5',
    messagingSenderId: '317294457408',
    projectId: 'project-1-212b6',
    databaseURL: 'https://project-1-212b6-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-212b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnUoLgWtVl0SYTy8nzKGraGhT3MNPdglI',
    appId: '1:317294457408:ios:bdf8bd8c27c5151c7365a5',
    messagingSenderId: '317294457408',
    projectId: 'project-1-212b6',
    databaseURL: 'https://project-1-212b6-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-212b6.appspot.com',
    iosClientId: '317294457408-9se10ip4em8nfckeri9n1burvm4g8t7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnUoLgWtVl0SYTy8nzKGraGhT3MNPdglI',
    appId: '1:317294457408:ios:bdf8bd8c27c5151c7365a5',
    messagingSenderId: '317294457408',
    projectId: 'project-1-212b6',
    databaseURL: 'https://project-1-212b6-default-rtdb.firebaseio.com',
    storageBucket: 'project-1-212b6.appspot.com',
    iosClientId: '317294457408-9se10ip4em8nfckeri9n1burvm4g8t7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
